# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-28 21:23
from __future__ import unicode_literals

import abastecimento.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abastecimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vale', models.CharField(blank=True, max_length=50, null=True, verbose_name='Vale/Cupom')),
                ('hodometro', models.IntegerField(default=0, validators=[abastecimento.models.validate_hodometro_and_veiculo_type], verbose_name='Hod\xf4metro/Horimetro')),
                ('quantidade', models.FloatField(verbose_name='Quantidade em Litros')),
                ('valor', models.FloatField(verbose_name='Valor Pago R$')),
                ('combustivel', models.CharField(choices=[('DS5', 'DS5'), ('ALC', 'Alcool'), ('DS1', 'DS1'), ('GSA', 'Gasolina Aditivada'), ('GSC', 'Gasolina Comum'), ('ARLA', 'ARLA'), ('LUB', 'LUB')], max_length=10)),
                ('notafiscal', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data Abastecimento')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Abastecimento Atualizado')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.CreateModel(
            name='Posto',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('placa', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Placa/Codigo Interno')),
                ('tipo', models.CharField(blank=True, choices=[('PROPRIO', 'Frota pr\xf3pria'), ('PROPRIO-SEM', 'Pr\xf3prio sem hor\xedmetro / od\xf4metro'), ('TERCEIRO-SEM', 'Terceirizados sem o desconto de combust\xedvel na medi\xe7\xe3o'), ('TERCEIRO-COM', 'Terceirizados com desconto do combust\xedvel na medi\xe7\xe3o')], max_length=13, null=True)),
                ('isVeiculo', models.BooleanField(choices=[(False, 'Maquina'), (True, 'Veiculo')], default=True, verbose_name='Veiculo/Maquina ')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('favorito', models.BooleanField(default=False, verbose_name='Favorito no grafico')),
                ('criado_date', models.DateField(auto_now_add=True, verbose_name='Data Criada')),
                ('atualizado_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Data Atualizado')),
            ],
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='abastecimento.Operador', verbose_name='Motorista/Operador'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Obra', verbose_name='Obra envolvida no abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='posto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Posto', verbose_name='Posto de abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Respons\xe1vel pelo abastecimento'),
        ),
        migrations.AddField(
            model_name='abastecimento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abastecimento.Veiculo', verbose_name='Veiculo/Equipamento'),
        ),
    ]
